### ISSUE TITLE
For customised HTML Generated document looks different than page displayed on website

### ISSUE THREAD

**Issue by dhitimedin** [KohheePeace/docusaurus-pdf#24]
Hi,

I had a requirement to wrap text around image. I used the following code type: 
<br clear="right"/>
<img align="left" src={useBaseUrl("img/scrnshts/3.7.3_PlantUtilization.png")} alt="Plant Utilization" width="45%"/>

![Rotate Screen](/img/scrnshts/App_RotateScreen.png)

<br/> 

> The utilization data for each component and variable is showcased.
>
> The utilization percentage will differ from plant to plant

<br clear="both"/>

The generated file breaks. Wherever a page break comes and there is space but not enough for the full image, the text that is wrapped around the image is pushed up to fill that empty space and the image is printed in the next page.

Do you have a work around for this? Let me know if you need a screen shot to understand.

**Comment by KohheePeace** [comment]
@dhitimedin Could you upload a screenshot??

**Comment by dhitimedin** [comment]
Thanks for your quick revert @KohheePeace . Let me know if the below screen shot helps. If not then I will try to publish the page and share the link with you.

[
![Screenshot 2020-11-06 at 8 13 28 AM](https://user-images.githubusercontent.com/68470624/98320093-2bb45d80-2008-11eb-9c54-9a831852492c.png)
![Screenshot 2020-11-06 at 8 12 49 AM](https://user-images.githubusercontent.com/68470624/98320106-366ef280-2008-11eb-9c2a-822223fc213c.png)

](url)

**Comment by KohheePeace** [comment]
@dhitimedin thanks for your report, I will tackle to refactor this plugin to solve currently reported issues. But it may take some time.


Do you have same issue with this plugin ? 
https://github.com/KohheePeace/mr-pdf

**Comment by dhitimedin** [comment]
> @dhitimedin thanks for your report, I will tackle to refactor this plugin to solve currently reported issues. But it may take some time.
> 
> Do you have same issue with this plugin ?
> https://github.com/KohheePeace/mr-pdf
Yes!

**Comment by KohheePeace** [comment]
> Do you have any specific timeline in mind?

=> Sorry I'm currently working on another project, so I'm not sure when it will be... 😿 Sorry...

> Do you have same issue with this plugin ?
https://github.com/KohheePeace/mr-pdf
Yes!

=> Do you think this issue can be solved by using CSS media queries like below?

```css
@media print { ... }
```

**Comment by dhitimedin** [comment]
> > Do you have any specific timeline in mind?
> 
> => Sorry I'm currently working on another project, so I'm not sure when it will be... 😿 Sorry...
> 
> > Do you have same issue with this plugin ?
> > https://github.com/KohheePeace/mr-pdf
> > Yes!
> 
> => Do you think this issue can be solved by using CSS media queries like below?
> 
> ```css
> @media print { ... }
> ```

Thank you for the pointer. I was able to work it out using CSS

**Comment by KohheePeace** [comment]
@dhitimedin Grad to hear that and hope for your star for my motivation 😉 👍
