### ISSUE TITLE
This plugin or mr-pdf

### ISSUE THREAD

**Issue by svict4** [KohheePeace/docusaurus-pdf#25]
Hey @KohheePeace I noticed that [`mr-pdf`](https://github.com/KohheePeace/mr-pdf) is more recent and looks like it has docusaurus support.
I was going to help with a PR, but would it be better if I migrated over to `mr-pdf`? Or do you think you'll support both plugins?

**Comment by KohheePeace** [comment]
hi @svict4, `docusaurus-pdf` is a plugin more focused on "docusaurus". For example `from-build command` or `docker support`.

`mr-pdf` is a plugin for more general use-case to generate PDF from document website. And it also doesn't have support like `from-build`.

So,
1. If the PR is docusaurus specific => `docusaurus-pdf`
2. If not => `mr-pdf`
