### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by jonsanjuan** [KohheePeace/docusaurus-pdf#5]
Hi Kohhee. I was trying to install your npm package and it was failing during the following install process. I am also rather new on Docusaurus and pdf translations, so thanks in advanced:

make: *** [Release/obj.target/hummus/src/PDFDictionaryDriver.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:321:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=/usr/local/lib/node_modules/hummus/binding" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/hummus
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/usr/local/lib/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack at ChildProcess. (/usr/local/lib/node_modules/hummus/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/hummus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/hummus
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/usr/local/lib/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.108 install: node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.108 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by KohheePeace** [comment]
@jonsanjuan 
what version of node are you using?

maybe this is similar issue
https://github.com/astefanutti/decktape/issues/184

**Comment by jonsanjuan** [comment]
On my Catalina computer I am running node v13.8.0

**Comment by adamwdennis** [comment]
I am also seeing this issue @KohheePeace -- using Node v14.0.0

**Comment by KohheePeace** [comment]
Sorry!, this is caused by the library which is used in `docusaurus-pdf` https://github.com/galkahana/HummusJS/issues/394

**Comment by krillboi** [comment]
Hi, just wanted to report that I'm seeing the same issue :)

Is there a workaround for this? Would love to check out your tool!

**Comment by jonsanjuan** [comment]
Is there a workaround or plans to do this in docusaurus 1?

**Comment by KohheePeace** [comment]
@krillboi @jonsanjuan 

1. Use old node version like `v10.19.0`
2. Make PR to add command like`docusaurus-pdf-v1`

Currently I have no guts to support v1 command. 😿  sorry.

This is example PR to add new command
https://github.com/KohheePeace/docusaurus-pdf/pull/4/files

**Comment by krillboi** [comment]
Just tried with 10.19.0 and no luck still.

```
$ npm install docusaurus-pdf --force
npm WARN using --force I sure hope you know what you are doing.
c:\programs\node-v10.19.0-win-x64\docusaurus-pdf -> c:\programs\node-v10.19.0-win-x64\node_modules\docusaurus-pdf\bin\index.js

> hummus@1.0.108 install c:\programs\node-v10.19.0-win-x64\node_modules\docusaurus-pdf\node_modules\hummus
> node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS

'"node"' is not recognized as an internal or external command,
operable program or batch file.

> puppeteer@2.1.1 install c:\programs\node-v10.19.0-win-x64\node_modules\docusaurus-pdf\node_modules\puppeteer
> node install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
+ docusaurus-pdf@1.1.1
added 147 packages from 75 contributors in 23.86s
```

**Comment by krillboi** [comment]
Okay, so I'm not sure it was actually the same issue we were facing, but I managed to run get the plugin installed by doing the following:

* Download the nodejs 10.19.0 binary
* Run `set NODE_TLS_REJECT_UNAUTHORIZED=0` in Node.js cmd (https://github.com/nodejs/help/issues/979#issuecomment-506108056 - note that this hack makes connections insecure, so use at own risk)
* Run `npm install docusaurus-pdf`

Seemed setting proxy settings in npm wasn't enough if you're behind one, and I need to set that variable to get through.

**Comment by KohheePeace** [comment]
@krillboi thanks for  sharing your knowledge!🎉 and sorry for I couldnt help!
